name: cd-workflow

on:
  workflow_run:
    workflows: ['ci-workflow']
    types:
      - completed
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-google-cloud-credential
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: install-google-cli
        uses: google-github-actions/setup-gcloud@v1
      - name: build-and-push-docker-image-to-artifact-registry
        run: make run-docker-push-to-artifact-registry
      - name: deploy-to-cloud-run
        run: make run-deploy-to-cloud-run